//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority
    {

        public int Id { get; set; }
        public string NamePriority { get; set; }
        public Nullable<int> Ordinal { get; set; }

        public List<Link> Links { get; set; }
    }
}
