//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {

        public virtual int id { get; set; }
        public virtual string subjectTask { get; set; }
        public virtual Nullable<System.DateTime> StartDate { get; set; }
        public virtual Nullable<System.DateTime> DueDate { get; set; }
        public virtual Nullable<System.DateTime> DateCompleted { get; set; }
        public virtual Nullable<System.DateTime> CreateDate { get; set; }
        public virtual Nullable<int> idPriority { get; set; }
        public virtual Nullable<int> idStatus { get; set; }
    
        public virtual Priority tbl_priority { get; set; }
        public virtual Status tbl_status { get; set; }
        public virtual ICollection<TaskUser> tbl_TaskUser { get; set; }
        public virtual ICollection<Category> tbl_category { get; set; }
    }
}
