//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskUser
    {
        public virtual int idTask { get; set; }
        public virtual string idUser { get; set; }
    
        public virtual Task tbl_task { get; set; }
    }
}
