//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Data.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.tbl_task = new HashSet<Task>();
        }
    
        public int id { get; set; }
        public string nameCategory { get; set; }
        public string descriptionCategory { get; set; }
    
        public virtual ICollection<Task> tbl_task { get; set; }
    }
}
