//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Data.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaskManagementDBEntities : DbContext
    {
        public TaskManagementDBEntities()
            : base("name=TaskManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> tbl_category { get; set; }
        public DbSet<Priority> tbl_priority { get; set; }
        public DbSet<Status> tbl_status { get; set; }
        public DbSet<Task> tbl_task { get; set; }
        public DbSet<TaskUser> tbl_TaskUser { get; set; }
    }
}
